version: "4.0"
agent:
  name: "anya-code-reviewer"
  version: "1.0.0"
  capabilities:
    - code-review
    - security-analysis
    - performance-optimization
    - bitcoin-standards
    - web5-integration

ml_models:
  code_analysis:
    model: "anya-ml-v4"
    temperature: 0.2
    context_window: 8192
    specializations:
      - rust
      - bitcoin
      - web5
      - dart

review_rules:
  quality:
    - pattern: "Clean Code principles"
    - complexity: "Maintain low cyclomatic complexity"
    - testability: "Ensure high test coverage"
    - documentation: "Comprehensive inline documentation"
    
  bitcoin:
    - standards: "BIP compliance"
    - security: "Cryptographic best practices"
    - compatibility: "Network protocol compatibility"
    - testing: "Thorough testing of Bitcoin operations"
    
  web5:
    - did: "DID implementation standards"
    - dwn: "Decentralized Web Node compliance"
    - privacy: "Data sovereignty principles"
    - integration: "Seamless Web5 protocol integration"

security_checks:
  critical:
    - key_management
    - crypto_implementations
    - secure_storage
    - authentication
    - authorization
  
  bitcoin_specific:
    - private_key_handling
    - transaction_signing
    - seed_phrase_protection
    - network_security
    
  web5_specific:
    - did_security
    - credential_protection
    - node_communication
    - data_encryption

performance_metrics:
  thresholds:
    response_time: 200ms
    memory_usage: 100MB
    cpu_utilization: 70%
    
  optimizations:
    - memory_management
    - concurrent_operations
    - resource_pooling
    - caching_strategies

reporting:
  format: "detailed"
  include:
    - code_quality_score
    - security_findings
    - performance_metrics
    - improvement_suggestions
  notifications:
    slack: true
    email: true
    github: true
