version: 1
labels:
  performance:
    - ".*performance improvement.*"
    - ".*optimize.*"
    - ".*faster.*"
    - ".*memory.*"
    - ".*cpu.*"
    - ".*speed.*"

  security:
    - ".*security.*"
    - ".*vulnerability.*"
    - ".*authentication.*"
    - ".*authorization.*"
    - ".*crypto.*"
    - ".*encrypt.*"

  ai-enhancement:
    - ".*machine learning.*"
    - ".*neural.*"
    - ".*model.*"
    - ".*training.*"
    - ".*inference.*"
    - ".*prediction.*"

  web5:
    - ".*did.*"
    - ".*decentralized.*"
    - ".*web5.*"
    - ".*dwn.*"
    - ".*identity.*"

  bitcoin:
    - ".*bitcoin.*"
    - ".*lightning.*"
    - ".*wallet.*"
    - ".*transaction.*"
    - ".*block.*"

  testing:
    - ".*test.*"
    - ".*coverage.*"
    - ".*assert.*"
    - ".*mock.*"
    - ".*stub.*"

  documentation:
    - ".*doc.*"
    - ".*comment.*"
    - ".*readme.*"
    - ".*api.*"
    - ".*guide.*"

  bug:
    - ".*fix.*"
    - ".*issue.*"
    - ".*error.*"
    - ".*crash.*"
    - ".*problem.*"

  enhancement:
    - ".*feature.*"
    - ".*add.*"
    - ".*new.*"
    - ".*implement.*"
    - ".*support.*"

  refactor:
    - ".*refactor.*"
    - ".*clean.*"
    - ".*reorganize.*"
    - ".*restructure.*"
    - ".*improve.*"

model:
  type: gpt-4
  settings:
    temperature: 0.2
    max_tokens: 100
    rules:
      - "Label based on PR title, description, and changed files"
      - "Consider technical impact and scope"
      - "Apply multiple labels if appropriate"
      - "Prioritize specific over general labels"
