repository:
  name: anya
  description: "Anya: AI-powered Bitcoin and Web5 Development Platform"
  homepage: https://anya.ai
  topics: bitcoin, web5, ai, rust, dart
  has_wiki: false
  has_projects: true
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_reviewers:
          - "@anya-core-team"
      required_status_checks:
        strict: true
        contexts: 
          - "Anya AI Review"
          - "Anya Security Scan"
          - "Anya Performance Check"
          - "continuous-integration/github-actions"
      enforce_admins: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      
  - name: "feature/*"
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - "Anya AI Review"
          - "Anya Security Scan"
      enforce_admins: false
      required_linear_history: true

labels:
  - name: "ai-approved"
    color: "0E8A16"
    description: "Approved by Anya AI"
  - name: "ai-changes-requested"
    color: "D93F0B"
    description: "Changes requested by Anya AI"
  - name: "security-critical"
    color: "B60205"
    description: "Critical security issue"
  - name: "performance-impact"
    color: "FFA500"
    description: "Performance impact detected"
