[package]
name = "anya-extensions"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }

