default: true

MD001: true  # header-increment
MD002: true  # first-header-h1
MD003:       # header-style
  style: "atx"
MD004:       # ul-style
  style: "dash"
MD005: true  # list-indent
MD006: true  # ul-start-left
MD007:       # ul-indent
  indent: 2
MD009: true  # no-trailing-spaces
MD010: true  # no-hard-tabs
MD011: true  # no-reversed-links
MD012:       # no-multiple-blanks
  maximum: 1
MD013: false # line-length
MD014: true  # commands-show-output
MD018: true  # no-missing-space-atx
MD019: true  # no-multiple-space-atx
MD020: true  # no-missing-space-closed-atx
MD021: true  # no-multiple-space-closed-atx
MD022: true  # blanks-around-headers
MD023: true  # header-start-left
MD024:       # no-duplicate-header
  siblings_only: true
MD025: true  # single-h1
MD026: true  # no-trailing-punctuation
MD027: true  # no-multiple-space-blockquote
MD028: true  # no-blanks-blockquote
MD029:       # ol-prefix
  style: "ordered"
MD030: true  # list-marker-space
MD031: true  # blanks-around-fences
MD032: true  # blanks-around-lists
MD033:       # no-inline-html
  allowed_elements:
    - div
    - span
    - p
    - a
    - img
    - button
    - br
    - details
    - summary
MD034: true  # no-bare-urls
MD035:       # hr-style
  style: "---"
MD036: true  # no-emphasis-as-header
MD037: true  # no-space-in-emphasis
MD038: true  # no-space-in-code
MD039: true  # no-space-in-links
MD040: true  # fenced-code-language
MD041: true  # first-line-h1
MD042: true  # no-empty-links
MD043: false # required-headers
MD044:       # proper-names
  names:
    - OPSource
    - GitHub
    - JavaScript
    - TypeScript
    - API
MD045: true  # no-alt-text
MD046:       # code-block-style
  style: "fenced"
MD047: true  # single-trailing-newline
MD048:       # code-fence-style
  style: "backtick"
MD049:       # emphasis-style
  style: "underscore"
MD050:       # strong-style
  style: "asterisk"
