name: Cross-Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      
      - name: Install cross
        run: cargo install cross
        
      - name: Build Linux x86_64
        run: cross build --target x86_64-unknown-linux-gnu
        
      - name: Run Tests
        run: cross test --target x86_64-unknown-linux-gnu
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-binaries
          path: target/x86_64-unknown-linux-gnu/release/anya

