name: Pull Request Automation

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Conventional Commits Check
        uses: webiny/action-conventional-commits@v1.3.0
        
      - name: PR Size Check
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/xs'
          xs_max_size: '10'
          s_label: 'size/s'
          s_max_size: '100'
          m_label: 'size/m'
          m_max_size: '500'
          l_label: 'size/l'
          l_max_size: '1000'
          xl_label: 'size/xl'
          
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Security Scan
        uses: github/codeql-action/analyze@v2
        with:
          languages: javascript, python, ruby
          queries: security-and-quality
          
  auto-merge:
    needs: [validate, security]
    runs-on: ubuntu-latest
    if: |
      github.event.review.state == 'approved' &&
      !github.event.pull_request.draft
    steps:
      - name: Auto-merge Pull Request
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_REQUIRED_APPROVALS: "2"
          MERGE_DELETE_BRANCH: "true"
          MERGE_LABELS: "approved,!work-in-progress"
