version: '3.8'

services:
  anya-core:
    image: anya-enterprise:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db/anya
      - BITCOIN_RPC_URL=http://bitcoin:8332
    depends_on:
      - db
      - bitcoin

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anya
    volumes:
      - db-data:/var/lib/postgresql/data

  bitcoin:
    image: ruimarinho/bitcoin-core:24.0
    command: bitcoind -printtoconsole -server -rpcallowip=::/0 -rpcbind=0.0.0.0
    ports:
      - "8332:8332"
      - "18443:18443" # Testnet
    volumes:
      - bitcoin-data:/bitcoin

volumes:
  db-data:
  bitcoin-data: