name: AI Code Review

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup reviewdog properly
      - name: Setup Reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: v0.14.1

      # Run reviewdog properly
      - name: Run Code Review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-review -filter-mode=nofilter -fail-on-error=false -level=warning

      # Fix CodeQL setup
      - name: Setup CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      # Proper CodeQL analysis step
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      # Replace unavailable CodiumAI action with github-script
      - name: Performance Check
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('Running performance checks on PR code...');
            // Performance check logic would go here

  label:
    needs: review
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true