name: Documentation Integrity
on: [push, pull_request]

jobs:
  documentation-checks:
    name: Verify Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Lint Documentation
      uses: reviewdog/action-markdownlint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        filter_mode: diff_context
        fail_on_error: true
        level: warning

    - name: Version Documentation
      if: github.ref == 'refs/heads/main'
      run: |
        chmod +x ./scripts/version-docs.sh
        ./scripts/version-docs.sh
      env:
        DOC_KEY: ${{ secrets.DOC_VERSION_KEY }}

    - name: Commit Versioned Docs
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name "Doc Version Bot"
        git config --global user.email "docbot@anya.org"
        git add docs/versions/
        git commit -m "docs: Auto-version documentation [skip ci]"
        git push 