name: Anya CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [core, mobile, dash33]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Check formatting
      run: cargo fmt --all -- --check
        
    - name: Lint
      run: cargo clippy --all-targets --all-features
      
    - name: Run tests
      run: cargo test --workspace
      
    - name: Security audit
      run: |
        cargo install cargo-audit
        cargo audit
        
  mobile-test:
    runs-on: macos-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install React Native dependencies
      run: |
        cd src/mobile
        yarn install
        
    - name: Run mobile tests
      run: |
        cd src/mobile
        yarn test
        
  dash33-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dashboard dependencies
      run: |
        cd packages/dash33
        yarn install
        
    - name: Run dashboard tests
      run: |
        cd packages/dash33
        yarn test

  build:
    needs: [test, mobile-test, dash33-test]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build all components
      run: cargo build --release --workspace
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: anya-release
        path: target/release/

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to staging
      run: echo "Deploying to staging environment"
      
  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
    
    steps:
    - name: Deploy to production
      run: echo "Deploying to production environment"
