name: Update Enterprise Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'docs/**'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx mermaid-cli pydoc-markdown

      - name: Generate API Documentation
        run: |
          sphinx-build -b html docs/source docs/build/html

      - name: Update Architecture Diagrams
        run: |
          find docs -name "*.md" -type f -exec sh -c '
            for file do
              mmdc -i "$file" -o "${file%.md}.png"
            done
          ' sh {} +

      - name: Update Metrics Documentation
        run: |
          python tools/update_metrics_docs.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: |
            docs: Update enterprise documentation

            - Update API documentation
            - Regenerate architecture diagrams
            - Update metrics documentation

            Generated by GitHub Actions
          title: "docs: Update enterprise documentation"
          body: |
            Automated documentation update for enterprise module:
            - Generated API documentation from docstrings
            - Updated architecture diagrams
            - Updated metrics documentation
            
            Please review the changes and merge if appropriate.
          branch: docs-update-enterprise
          base: main
