[workspace]
members = [
    "src/bitcoin/anya-bitcoin",
    "src/enterprise/anya-enterprise",
    "src/extensions/anya-extensions"
]

[workspace.dependencies]
bitcoin = "0.30.0"
lightning = "0.0.116"
rgb-core = "0.10"
taproot = "0.1.0"
web5 = "0.1.0"
handshake-client = "0.1.0"
rsk = "0.1.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
