[package]
name = "anya-core"
version = "0.1.0"
edition = "2021"
authors = ["Anya Core Team"]
description = "Core functionality for the Anya platform"

[workspace]
members = [
    "dependencies/anya-bitcoin",
    "dependencies/anya-extensions"
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.72"
thiserror = "1.0.44"
tokio = { version = "1.41.1", features = ["full"] }
async-trait = "0.1.77"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
chrono = { version = "0.4.26", features = ["serde"] }
log = "0.4.19"
actix-web = "4.4.0"
actix-cors = "0.6.4"
clap = { version = "4.3.21", features = ["derive"] }
bitcoin = { version = "0.32.1", features = ["rand"] }

[[bin]]
name = "installer"
path = "src/bin/installer.rs"

[[bin]]
name = "api_server"
path = "src/bin/api_server.rs"

[dependencies]
# Bitcoin dependencies
bitcoincore-rpc = "0.17.0"
secp256k1 = { version = "0.27.0", features = ["rand"] }
bdk = { version = "0.30.2" }
bitcoin.workspace = true

# Lightning dependencies
lightning = { version = "0.0.116" }
lightning-persister = { version = "0.0.116" }
lightning-background-processor = { version = "0.0.116" }
lightning-block-sync = { version = "0.0.116" }
lightning-invoice = { version = "0.26.0" }
lightning-net-tokio = { version = "0.0.116" }

# Cross-chain dependencies
rgb-core = "0.10"
rsk = "0.1.0"
taproot = "0.1.0"
elements = "0.22.0"  # Liquid/Elements dependency
elements-rpc = "0.1.0"  # Liquid/Elements RPC client

# Web5 dependencies
web5 = { git = "https://github.com/decentralized-identity/web5-rs", package = "web5" }
base64 = "0.21.7"
sha2 = "0.10.8"
ed25519-dalek = "2.1.1"
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
multibase = "0.9.1"
multihash = "0.18.1"
reqwest = { version = "0.11.24", features = ["json"] }

# Web tools
jwt = "0.16.0"
toml = "0.7.6"
uuid = { version = "1.4.1", features = ["v4"] }
env_logger = "0.10.0"
actix-web.workspace = true
actix-cors.workspace = true
clap.workspace = true

# DLC specific
secp256k1-zkp = { version = "0.7.0", features = ["global-context"] }
bdk-macros = "0.6.0"
miniscript = "10.0.0"

# Utilities
rand = "0.8"
futures = "0.3"
hex = "0.4.3"
tokio.workspace = true
async-trait.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true

[lib]
name = "anya_core"
path = "src/lib.rs"

[features]
default = ["bitcoin-full", "web5", "liquid"]
bitcoin-full = []
lightning = []
dlc = []
taproot-assets = []
cross-chain = []
web5 = []
liquid = []

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = false
panic = "abort"

[profile.dev.package."*"]
opt-level = 3