[package]
name = "anya-core"
version = "0.1.0"
edition = "2021"
description = "Core AI functionality for the Anya project"
authors = ["Botshelo Mokoka <botshelo@codeium.com>"]
license = "MIT"

[dependencies]
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
metrics = { workspace = true }
actix-web = { workspace = true }
prometheus = { workspace = true }
reqwest = { workspace = true }
web5 = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
ndarray = { workspace = true }
tch = { workspace = true }
rand = { workspace = true }
futures = { workspace = true }
ring = { workspace = true }
jsonwebtoken = { workspace = true }
mockall = { workspace = true }
tokio-test = { workspace = true }
bitcoin = { workspace = true }
http = { workspace = true }

[features]
default = ["metrics"]
metrics = []
