[package]
name = "anya-core"
version = "0.1.0"
edition = "2021"
description = "Core module for the Anya platform, integrating Bitcoin, AI, Web5, Mobile, and Enterprise features."
authors = ["bo_thebig <botshelomokoka@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/botshelomokoka/OPSource"
documentation = "https://docs.rs/anya"
readme = "README.md"
keywords = ["bitcoin", "ai", "web5", "mobile", "enterprise", "core"]
categories = ["cryptography", "blockchain", "web-programming"]

[workspace]
members = [
    # ".", # Remove this line as this Cargo.toml is for anya-core itself
    "../anya-enterprise",
    "../anya-extensions",
    "../anya-bitcoin",
    "../dash33",
    "../mobile",
    "../src/core",
    "../src/mobile"
]
resolver = "2"

[workspace.dependencies]
# Core dependencies
tokio = { version = "1.41.1", features = ["full", "macros"] }
futures = "0.3.30"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_yaml = "0.9.25"
anyhow = "1.0.75"
thiserror = "1.0.75" # Version aligned
async-trait = "0.1.77"

# Blockchain Integration
bitcoin = { version = "0.32.1", features = ["rand"] }
bitcoincore-rpc = "0.17.0" # Version aligned
secp256k1 = { version = "0.27.0", features = ["rand"] } # Version aligned
lightning = "0.0.116" # Version aligned
rgb-core = "0.10"
taproot = "0.1.0"

# Web5 Integration
web5 = { git = "https://github.com/TBD54566975/web5-rs", tag = "v4.0.0" }
did-key = "0.2"

# DAO Integration
clarinet-sdk = "1.0.1"
stacks-core = "0.1.0"
dao-governance = { git = "https://github.com/stacks-network/dao-contracts", branch = "main" }
clarity-lang = "1.0.0"

# Stacks and DAO dependencies
stacks-common = "0.0.3"
clarity-sdk = "1.0.0"
dao-contracts = { git = "https://github.com/stacks-network/dao-contracts", branch = "main" }

[dependencies]
# Core dependencies
tokio = { version = "1.41.1", features = ["full"] }
serde = { version = "1.0.215", features = ["derive"] }
chrono = { version = "0.4.31", features = ["serde"] }

# DAO and ML dependencies
stacks-common = { workspace = true }
clarity-sdk = { workspace = true }
dao-contracts = { git = "https://github.com/stacks-network/dao-contracts", branch = "main" }
tch = "0.19.0"  # PyTorch bindings for Rust
ndarray = "0.16.1"
smartcore = "0.4.0"

# Additional deps kept minimal
uuid = { version = "1.8.0", features = ["v4"] }
tracing = { version = "0.1.40", features = ["attributes"] }

# DAO Dependencies
clarinet-sdk = { workspace = true }
stacks-core = { workspace = true }
dao-governance = { workspace = true }
clarity-lang = { workspace = true }

# Stacks and DAO dependencies
stacks-common = { workspace = true }
clarity-sdk = { workspace = true }
dao-contracts = { workspace = true }
stacks-network = { workspace = true }

[dev-dependencies]
tokio-test = "0.4.3"
mockall = "0.13.1"
criterion = "0.5.1"

[features]
default = ["std"]
std = []
dao = ["std"]  # No longer depends on stacks directly
ml = ["std"]
full = ["dao", "ml"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
