version: '3.8'

services:
  anya-core:
    image: anya-enterprise:debug
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "9229:9229"  # Debug port
    environment:
      - NODE_ENV=development
      - DEBUG=true
      - BITCOIN_RPC_URL=http://bitcoin:8332
      - WEB5_DWN_URL=http://dwn:3000
      - WEB5_STORAGE_PATH=/data/web5
    volumes:
      - .:/app
      - web5-data:/data/web5
    command: ["cargo", "run", "--debug"]
    depends_on:
      - bitcoin
      - dwn

  dwn:
    image: web5/dwn:latest
    ports:
      - "3000:3000"
      - "9230:9229"  # Debug port
    volumes:
      - web5-data:/data
      - .:/app
    environment:
      - NODE_ENV=development
      - DEBUG=true
      - DWN_STORAGE_PATH=/data

  bitcoin:
    image: ruimarinho/bitcoin-core:24.0
    command: bitcoind -printtoconsole -server -rpcallowip=::/0 -rpcbind=0.0.0.0 -debug=1
    ports:
      - "8332:8332"
      - "18443:18443"  # Testnet
    volumes:
      - bitcoin-data:/bitcoin
      - .:/app/bitcoin

volumes:
  web5-data:
  bitcoin-data:
