name: anya
description: Enterprise-grade Bitcoin Infrastructure Platform
version: 0.2.0
homepage: https://github.com/botshelomokoka/anya-core

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  http: ^1.2.0
  yaml: ^3.1.2
  logging: ^1.2.0
  path: ^1.8.3
  crypto: ^3.0.3
  web5: ^0.4.0
  bitcoin_base: ^5.0.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  fl_chart: ^0.70.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  hex: ^0.2.0
  pointycastle: ^3.7.3
  cryptography: ^2.7.0
  bip39: ^1.0.6
  bip32: ^2.0.0
  # Added for type safety and code generation
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  meta: ^1.9.1
  async: ^2.11.0
  collection: ^1.18.0

dev_dependencies:
  test: ^1.24.0
  lints: ^5.1.1
  build_runner: ^2.4.6
  mockito: ^5.3.0
  json_serializable: ^6.6.0
  freezed: ^2.4.5
  coverage: ^1.6.3
  dart_code_metrics: ^4.0.0

executables:
  anya: anya

topics:
  - bitcoin
  - web5
  - cryptocurrency
  - blockchain
