# Production Environment Configuration

# Production network settings
network:
  capacity: 10000
  node_connection_limit: 1000
  performance_threshold: 0.8
  false_positive_threshold: 0.9
  ssl_enabled: true
  connection_timeout: 30

# Production database settings
database:
  host: "${DB_HOST}"
  port: "${DB_PORT}"
  max_connections: 100
  pool_timeout: 60
  ssl_mode: "verify-full"
  connection_retry:
    max_attempts: 5
    backoff_seconds: 5

# Production logging
logging:
  level: "info"
  format: "json"
  output: "file"
  file_logging:
    enabled: true
    path: "/var/log/anya/production.log"
    rotation:
      max_size: "1GB"
      max_files: 30
      compression: true

# Security settings
security:
  jwt_expiration: 3600  # 1 hour
  password_hash_rounds: 12
  enable_cors: true
  allowed_origins: ["https://app.anya.io"]
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst: 20
  ssl:
    enabled: true
    cert_path: "/etc/ssl/anya/cert.pem"
    key_path: "/etc/ssl/anya/key.pem"

# Cache settings
cache:
  enabled: true
  type: "redis"
  url: "${REDIS_URL}"
  max_size: "10GB"
  ttl: 3600
  cluster:
    enabled: true
    nodes: 3

# Feature flags
features:
  experimental_ml: false
  advanced_optimization: true
  quantum_resistant: true
  enhanced_security: true
  debug_mode: false
  maintenance_mode: false

# Performance optimization
performance:
  connection_pooling: true
  query_cache_size: "2GB"
  worker_threads: 32
  task_queue_size: 10000
  batch_processing:
    enabled: true
    max_batch_size: 1000
    timeout_ms: 500

# Monitoring and metrics
monitoring:
  metrics_collection: true
  tracing_enabled: true
  apm_enabled: true
  error_reporting:
    enabled: true
    service: "sentry"
    dsn: "${SENTRY_DSN}"
  alerting:
    enabled: true
    channels:
      - type: "email"
        recipients: ["ops@anya.io"]
      - type: "slack"
        webhook: "${SLACK_WEBHOOK}"
  health_checks:
    enabled: true
    interval_seconds: 60
    endpoints:
      - "/health"
      - "/readiness"
      - "/liveness"

# Backup configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention:
    daily: 7
    weekly: 4
    monthly: 12
  storage:
    type: "s3"
    bucket: "${BACKUP_BUCKET}"
    region: "${AWS_REGION}"
