name: Automated Pull Request

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Auto PR: ${{ github.ref_name }}'
          body: |
            Automated Pull Request from branch: ${{ github.ref_name }}
            
            Changes included in this PR:
            ${{ github.event.head_commit.message }}
          base: main
          branch: ${{ github.ref_name }}
          labels: automated-pr
          draft: false
