name: Branch Cleanup and Changelog

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  cleanup-branches:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Delete merged branch
        run: git push origin --delete ${{ github.event.pull_request.head.ref }}
        
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Generate changelog
        uses: conventional-changelog/conventional-changelog-action@v3
        with:
          config: conventional-changelog-conventionalcommits
          release-count: 0
          git-message: 'chore(release): update CHANGELOG.md'
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore(docs): update changelog'
          title: 'chore(docs): update changelog'
          body: 'Update CHANGELOG.md with latest changes'
          branch: 'chore/update-changelog'
          base: main
