name: Documentation Validation

on:
  push:
    paths:
      - 'docs/**'
      - 'README.md'
      - '**/*.md'
      - '.github/workflows/docs-validation.yml'
  pull_request:
    paths:
      - 'docs/**'
      - 'README.md'
      - '**/*.md'
      - '.github/workflows/docs-validation.yml'

jobs:
  validate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions markdown
          npm install -g markdown-link-check markdownlint-cli
          
      - name: Check Markdown links
        run: |
          find . -name "*.md" -type f -not -path "./node_modules/*" -exec markdown-link-check {} \;
        continue-on-error: true
          
      - name: Lint Markdown files
        run: |
          markdownlint "**/*.md" --ignore node_modules
        continue-on-error: true
          
      - name: Build documentation preview
        run: |
          mkdocs build
          
      - name: Upload documentation preview
        uses: actions/upload-artifact@v3
        with:
          name: documentation-preview
          path: site/
