name: OPSource CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Run tests
      run: pytest
      
    - name: Check code style
      run: |
        pip install black
        black --check .
        
    - name: Security check
      run: |
        pip install bandit
        bandit -r src/
        
  research:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Run research notebooks
      run: |
        pip install jupyter
        jupyter nbconvert --execute notebooks/*.ipynb --to html
        
    - name: Upload research results
      uses: actions/upload-artifact@v3
      with:
        name: research-results
        path: notebooks/*.html

  deploy:
    needs: [test, research]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy research platform
      run: echo "Deploying research platform"
