name: Pull Request Validation

on:
  pull_request:
    branches: [ main, develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          - feat
          - fix
          - docs
          - style
          - refactor
          - perf
          - test
          - build
          - ci
          - chore
          - revert
          - deps
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 pylint pytest
    
    - name: Check code formatting
      run: black --check .
      continue-on-error: true
    
    - name: Check code quality
      run: |
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
      continue-on-error: true
    
    - name: Validate requirements
      run: |
        echo "Checking for Windows-specific packages without environment markers"
        if grep -q "pywin32==" requirements.txt && ! grep -q "pywin32==.*sys_platform" requirements.txt; then
          echo "::warning::pywin32 should have environment marker 'sys_platform == \"win32\"'"
        fi
        if grep -q "win32_setctime==" requirements.txt && ! grep -q "win32_setctime==.*sys_platform" requirements.txt; then
          echo "::warning::win32_setctime should have environment marker 'sys_platform == \"win32\"'"
        fi
      continue-on-error: true
