name: Update TODOs

on:
  push:
    branches: [ main, development ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  update-todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          
      - name: Run TODO migration
        run: python .github/scripts/todo_migration.py
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/TODO.md docs/archived_todos/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update TODO report"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
