name: TODO Automation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.md'
      - '**/*.py'
      - '**/*.rs'
      - '**/*.js'
      - '**/*.ts'

jobs:
  todo-automation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml markdown beautifulsoup4 GitPython
    
    - name: Run TODO migration
      run: |
        python .github/scripts/todo_migration.py
      continue-on-error: true
    
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update TODOs and documentation [skip ci]"
        file_pattern: "**/*.md"
        branch: ${{ github.head_ref }}
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"
        commit_author: "GitHub Actions <actions@github.com>"
