name: Version Management

on:
  push:
    branches:
      - main

jobs:
  version-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get latest version
        id: get_version
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT
          
      - name: Bump version
        id: bump_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          
      - name: Update submodules
        if: steps.bump_version.outputs.new_tag != steps.get_version.outputs.LATEST_TAG
        run: |
          git submodule foreach 'git fetch origin && git checkout $(git describe --tags --abbrev=0 || echo main)'
          git add .
          git commit -m "chore(deps): update submodules to latest tags"
          git push
